# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to Bisect-Comics
description: Ever forget which comic you read last? Well worry no more, this project is aimed at making sure you can go through chronologically using a binary search to find the last-read comic.
show_downloads: "true"

theme: jekyll-theme-cayman